version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:stable

orbs:
  coveralls: coveralls/coveralls@1.0.4
  node: circleci/node@4.5.1

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run: yarn
      - run: yarn test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              node-version: ['14.17.1', '15.14.0', '16.3.0']
