version: 2.1

orbs:
  node: circleci/node@2.0.0

jobs:
  test:
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run: yarn test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]
