version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:stable

orbs:
  node: circleci/node@4.5.1

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: linux
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - restore_cache:
          keys:
            - << parameters.node-version >>-dependencies-{{ checksum "yarn.lock" }}
            - << parameters.node-version >>-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: << parameters.node-version >>-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn type
      - run: yarn test --coverage
      - run: yarn build
  publish:
    executor: linux
    steps:
      - checkout
      - node/install:
          node-version: 16.3.0
          install-yarn: true
      - restore_cache:
          keys:
            - current-dependencies-{{ checksum "yarn.lock" }}
            - current-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: current-dependencies-{{ checksum "yarn.lock" }}
      - run: npm publish

workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ['14.17.1', '15.14.0', '16.3.0']
      - publish:
          filters:
            branches:
              only:
                - main
          requires:
            - test
